/* The list of products used the first time doing this assignment, later the products where fetched from an api */

export const productArray = [
    {
        name: "Jacket",
        description: "Nice jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 499,
        id: "1",
        quantity: 1,
        gender: "man",
    },
    {
        name: "Rainy jacket",
        description: "Nice wet jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 599,
        id: "2",
        quantity: 1,
        gender: "man",
    },
    {
        name: "Hot jacket",
        description: "Nice warm jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 666,
        id: "3",
        quantity: 1,
        gender: "man",
    },
    {
        name: "Cool jacket",
        description: "Nice cool jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 299,
        id: "4",
        quantity: 1,
        gender: "man",
    },
    {
        name: "Dry jacket",
        description: "Nice dry jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 399,
        id: "5",
        quantity: 1,
        gender: "man",
    },
    {
        name: "The jacket",
        description: "it`s the jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 999,
        id: "6",
        quantity: 1,
        gender: "man",
    },
    {
        name: "Windy jacket",
        description: "Nice windy jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 799,
        id: "7",
        quantity: 1,
        gender: "man",
    },
    {
        name: "Cloudy jacket",
        description: "Comfy cloudy jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 899,
        id: "8",
        quantity: 1,
        gender: "man",
    },
    {
        name: "Shiny jacket",
        description: "Nice shiny jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 499,
        id: "9",
        quantity: 1,
        gender: "man",
    },
    {
        name: "Noisy jacket",
        description: "Very noisy jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 400,
        id: "10",
        quantity: 1,
        gender: "man",
    },
    {
        name: "Jacket",
        description: "Nice jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 499,
        id: "11",
        quantity: 1,
        gender: "woman",
    },
    {
        name: "Rainy jacket",
        description: "Nice wet jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 599,
        id: "12",
        quantity: 1,
        gender: "woman",
    },
    {
        name: "Hot jacket",
        description: "Nice warm jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 666,
        id: "13",
        quantity: 1,
        gender: "woman",
    },
    {
        name: "Cool jacket",
        description: "Nice cool jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 299,
        id: "14",
        quantity: 1,
        gender: "woman",
    },
    {
        name: "Dry jacket",
        description: "Nice dry jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 399,
        id: "15",
        quantity: 1,
        gender: "woman",
    },
    {
        name: "The jacket",
        description: "it`s the jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 999,
        id: "16",
        quantity: 1,
        gender: "woman",
    },
    {
        name: "Windy jacket",
        description: "Nice windy jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 799,
        id: "17",
        quantity: 1,
        gender: "woman",
    },
    {
        name: "Cloudy jacket",
        description: "Comfy cloudy jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 899,
        id: "18",
        quantity: 1,
        gender: "woman",
    },
    {
        name: "Shiny jacket",
        description: "Nice shiny jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 499,
        id: "19",
        quantity: 1,
        gender: "woman",
    },
    {
        name: "Noisy jacket",
        description: "Very noisy jacket",
        long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 400,
        id: "20",
        quantity: 1,
        gender: "woman",
    },

];