export const productArray = [
    {
        name: "Jacket",
        description: "Nice jacket",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 499,
        id: "1",
        quantity: 1,
        gender: "man",
    },
    {
        name: "Rainy jacket",
        description: "Nice wet jacket",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 599,
        id: "2",
        quantity: 1,
        gender: "man",
    },
    {
        name: "Hot jacket",
        description: "Nice warm jacket",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 666,
        id: "3",
        quantity: 1,
        gender: "man",
    },
    {
        name: "Cool jacket",
        description: "Nice cool jacket",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 299,
        id: "4",
        quantity: 1,
        gender: "man",
    },
    {
        name: "Dry jacket",
        description: "Nice dry jacket",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 399,
        id: "5",
        quantity: 1,
        gender: "man",
    },
    {
        name: "The jacket",
        description: "it`s the jacket",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 999,
        id: "6",
        quantity: 1,
        gender: "man",
    },
    {
        name: "Windy jacket",
        description: "Nice windy jacket",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 799,
        id: "7",
        quantity: 1,
        gender: "man",
    },
    {
        name: "Cloudy jacket",
        description: "Comfy cloudy jacket",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 899,
        id: "8",
        quantity: 1,
        gender: "man",
    },
    {
        name: "Shiny jacket",
        description: "Nice shiny jacket",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 499,
        id: "9",
        quantity: 1,
        gender: "man",
    },
    {
        name: "Noisy jacket",
        description: "Very noisy jacket",
        image: "./images/product-man.jpg",
        big_image: "./images/details-man.jpg",
        price: 400,
        id: "10",
        quantity: 1,
        gender: "man",
    },
    {
        name: "Jacket",
        description: "Nice jacket",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 499,
        id: "11",
        quantity: 1,
        gender: "woman",
    },
    {
        name: "Rainy jacket",
        description: "Nice wet jacket",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 599,
        id: "12",
        quantity: 1,
        gender: "woman",
    },
    {
        name: "Hot jacket",
        description: "Nice warm jacket",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 666,
        id: "13",
        quantity: 1,
        gender: "woman",
    },
    {
        name: "Cool jacket",
        description: "Nice cool jacket",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 299,
        id: "14",
        quantity: 1,
        gender: "woman",
    },
    {
        name: "Dry jacket",
        description: "Nice dry jacket",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 399,
        id: "15",
        quantity: 1,
        gender: "woman",
    },
    {
        name: "The jacket",
        description: "it`s the jacket",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 999,
        id: "16",
        quantity: 1,
        gender: "woman",
    },
    {
        name: "Windy jacket",
        description: "Nice windy jacket",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 799,
        id: "17",
        quantity: 1,
        gender: "woman",
    },
    {
        name: "Cloudy jacket",
        description: "Comfy cloudy jacket",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 899,
        id: "18",
        quantity: 1,
        gender: "woman",
    },
    {
        name: "Shiny jacket",
        description: "Nice shiny jacket",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 499,
        id: "19",
        quantity: 1,
        gender: "woman",
    },
    {
        name: "Noisy jacket",
        description: "Very noisy jacket",
        image: "./images/product-woman.jpg",
        big_image: "./images/details-woman.jpg",
        price: 400,
        id: "20",
        quantity: 1,
        gender: "woman",
    },
    
];